### ISSUE TITLE
es5-compatible "build.js" (or something similar)

### ISSUE THREAD

**Issue by stephenmathieson** [juliangruber/co-from-stream#1]
would you be up for it?  just use `regenerator` and do something like:

**index.js**

``` js
module.exports = require('generator-supported') ? require('./es6') : require('./es5')
```

**Comment by juliangruber** [comment]
have you seen https://github.com/TooTallNate/gnode?

**Comment by stephenmathieson** [comment]
yup, but i'm hoping to not require people to install it.  basically, what i'm trying to do is support node 10 in a project which uses generators.

**Comment by stephenmathieson** [comment]
anyway, if you're interested: https://gist.github.com/stephenmathieson/4c296844ce376713500a

**Comment by juliangruber** [comment]
i see, but i prefer central changes instead of relying on every lib you use to follow your requirements

**Comment by stephenmathieson** [comment]
yeah, I get it. just sort of a bummer as anything using `co-fs` with or without using its streams cannot be built into a node 0.10 compatible module.

**Comment by matthewmueller** [comment]
I agree with @juliangruber. Can't we do what @dominicbarnes did with duo-package?

**Comment by stephenmathieson** [comment]
@MatthewMueller yeah, but by [`require`-ing co-fs](https://github.com/component/duo-cache/blob/master/index.js#L14) (which requires this lib), well throw syntax errors :/

**Comment by dominicbarnes** [comment]
Any thoughts on requiring [gnode](https://github.com/TooTallNate/gnode) for node v0.10 support? (I believe it compiles files on-demand, so we could remove the build step in theory)

I mean, once 0.12 is out, we won't bother supporting 0.10 anymore right, so it could be a temporary thing? (although who knows when the heck that'll finally happen!)
